const fetch = require("node-fetch");

module.exports = function (msg, ort) {
  let Ortschaft = ort[1];
  for (i = 2; ort[i] != undefined;) {
    Ortschaft = Ortschaft + " " + ort[i];
    console.log("in if  " + Ortschaft);
    i++
  }
  //if (ort[2] != undefined) {
  //Ortschaft = Ortschaft + " " + ort[2];
  //console.log("in if  " + Ortschaft);
  //}
  let cityid = getID(ort[0], Ortschaft);
  console.log("zu getID  " + Ortschaft);
  console.log(cityid);
  if (cityid == undefined) {
    msg.channel.send("So nicht!");
  } else {
    useData(cityid, msg);
  }
}

function getID(type, name) {
  let stadtids = {
    "Flensburg": 1,
    "Kiel": 2,
    "Lübeck": 3,
    "Neumünster": 4,
    "Hamburg": 16,
    "Braunschweig": 17,
    "Salzgitter": 18,
    "Wolfsburg": 19,
    "Delmenhorst": 45,
    "Emden": 46,
    "Oldenburg (Oldb)": 47,
    "Osnabrück": 48,
    "Wilhelmshaven": 49,
    "Bremen": 62,
    "Bremerhaven": 63,
    "Düsseldorf": 64,
    "Duisburg": 65,
    "Essen": 66,
    "Krefeld": 67,
    "Mönchengladbach": 68,
    "Mülheim an der Ruhr": 69,
    "Oberhausen": 70,
    "Remscheid": 71,
    "Solingen": 72,
    "Wuppertal": 73,
    "Bonn": 79,
    "Köln": 80,
    "Leverkusen": 81,
    "Bottrop": 90,
    "Gelsenkirchen": 91,
    "Münster": 92,
    "Bielefeld": 98,
    "Bochum": 105,
    "Dortmund": 106,
    "Hagen": 107,
    "Hamm": 108,
    "Herne": 109,
    "Darmstadt": 117,
    "Frankfurt am Main": 118,
    "Offenbach am Main": 119,
    "Wiesbaden": 120,
    "Kassel": 136,
    "Koblenz": 143,
    "Trier": 154,
    "Frankenthal (Pfalz)": 159,
    "Kaiserslautern": 160,
    "Landau in der Pfalz": 161,
    "Ludwigshafen am Rhein": 162,
    "Mainz": 163,
    "Neustadt an der Weinstraße": 164,
    "Pirmasens": 165,
    "Speyer": 166,
    "Worms": 167,
    "Zweibrücken": 168,
    "Ingolstadt": 223,
    "München": 224,
    "Rosenheim": 225,
    "Landshut": 246,
    "Passau": 247,
    "Straubing": 248,
    "Amberg": 258,
    "Regensburg": 259,
    "Weiden i.d. OPf.": 260,
    "Bamberg": 268,
    "Bayreuth": 269,
    "Coburg": 270,
    "Hof": 271,
    "Ansbach": 281,
    "Erlangen": 282,
    "Fürth": 283,
    "Nürnberg": 284,
    "Schwabach": 285,
    "Aschaffenburg": 293,
    "Schweinfurt": 294,
    "Würzburg": 295,
    "Augsburg": 305,
    "Kaufbeuren": 306,
    "Kempten (Allgäu)": 307,
    "Memmingen": 308,
    "Brandenburg an der Havel": 326,
    "Cottbus": 327,
    "Frankfurt (Oder)": 328,
    "Potsdam": 329,
    "Rostock": 344,
    "Schwerin": 345,
    "Chemnitz": 352,
    "Dresden": 357,
    "Leipzig": 362,
    "Dessau-Roßlau": 365,
    "Halle (Saale)": 366,
    "Magdeburg": 367,
    "Erfurt": 379,
    "Gera": 380,
    "Jena": 381,
    "Suhl": 382,
    "Weimar": 383,
    "Eisenach": 384
  }
  let lkids = {
    "Gifhorn": 20,
    "Goslar": 21,
    "Helmstedt": 22,
    "Northeim": 23,
    "Peine": 24,
    "Wolfenbüttel": 25,
    "Göttingen": 26,
    "Region Hannover": 27,
    "Diepholz": 28,
    "Hameln-Pyrmont": 29,
    "Hildesheim": 30,
    "Holzminden": 31,
    "Nienburg (Weser)": 32,
    "Schaumburg": 33,
    "Celle": 34,
    "Cuxhaven": 35,
    "Harburg": 36,
    "Lüchow-Dannenberg": 37,
    "Lüneburg": 38,
    "Osterholz": 39,
    "Rotenburg (Wümme)": 40,
    "Heidekreis": 41,
    "Stade": 42,
    "Uelzen": 43,
    "Verden": 44,
    "Ammerland": 50,
    "Aurich": 51,
    "Cloppenburg": 52,
    "Emsland": 53,
    "Friesland": 54,
    "Grafschaft Bentheim": 55,
    "Leer": 56,
    "Oldenburg": 57,
    "Osnabrück": 58,
    "Vechta": 59,
    "Wesermarsch": 60,
    "Wittmund": 61,
    "Bergstraße": 121,
    "Darmstadt-Dieburg": 122,
    "Groß-Gerau": 123,
    "Hochtaunuskreis": 124,
    "Main-Kinzig-Kreis": 125,
    "Main-Taunus-Kreis": 126,
    "Odenwaldkreis": 127,
    "Offenbach": 128,
    "Rheingau-Taunus-Kreis": 129,
    "Wetteraukreis": 130,
    "Gießen": 131,
    "Lahn-Dill-Kreis": 132,
    "Limburg-Weilburg": 133,
    "Marburg-Biedenkopf": 134,
    "Vogelsbergkreis": 135,
    "Fulda": 137,
    "Hersfeld-Rotenburg": 138,
    "Kassel": 139,
    "Schwalm-Eder-Kreis": 140,
    "Waldeck-Frankenberg": 141,
    "Werra-Meißner-Kreis": 142,
    "Ahrweiler": 144,
    "Altenkirchen (Westerwald)": 145,
    "Bad Kreuznach": 146,
    "Birkenfeld": 147,
    "Cochem-Zell": 148,
    "Mayen-Koblenz": 149,
    "Neuwied": 150,
    "Rhein-Hunsrück-Kreis": 151,
    "Rhein-Lahn-Kreis": 152,
    "Westerwaldkreis": 153,
    "Bernkastel-Wittlich": 155,
    "Eifelkreis Bitburg-Prüm": 156,
    "Vulkaneifel": 157,
    "Trier-Saarburg": 158,
    "Alzey-Worms": 169,
    "Bad Dürkheim": 170,
    "Donnersbergkreis": 171,
    "Germersheim": 172,
    "Kaiserslautern": 173,
    "Kusel": 174,
    "Südliche Weinstraße": 175,
    "Rhein-Pfalz-Kreis": 176,
    "Mainz-Bingen": 177,
    "Südwestpfalz": 178,
    "Böblingen": 180,
    "Esslingen": 181,
    "Göppingen": 182,
    "Ludwigsburg": 183,
    "Rems-Murr-Kreis": 184,
    "Heilbronn": 186,
    "Hohenlohekreis": 187,
    "Schwäbisch Hall": 188,
    "Main-Tauber-Kreis": 189,
    "Heidenheim": 190,
    "Ostalbkreis": 191,
    "Karlsruhe": 194,
    "Rastatt": 195,
    "Neckar-Odenwald-Kreis": 198,
    "Rhein-Neckar-Kreis": 199,
    "Calw": 201,
    "Enzkreis": 202,
    "Freudenstadt": 203,
    "Breisgau-Hochschwarzwald": 205,
    "Emmendingen": 206,
    "Ortenaukreis": 207,
    "Rottweil": 208,
    "Schwarzwald-Baar-Kreis": 209,
    "Tuttlingen": 210,
    "Konstanz": 211,
    "Lörrach": 212,
    "Waldshut": 213,
    "Reutlingen": 214,
    "Tübingen": 215,
    "Zollernalbkreis": 216,
    "Alb-Donau-Kreis": 218,
    "Biberach": 219,
    "Bodenseekreis": 220,
    "Ravensburg": 221,
    "Sigmaringen": 222,
    "Altötting": 226,
    "Berchtesgadener Land": 227,
    "Bad Tölz-Wolfratshausen": 228,
    "Dachau": 229,
    "Ebersberg": 230,
    "Eichstätt": 231,
    "Erding": 232,
    "Freising": 233,
    "Fürstenfeldbruck": 234,
    "Garmisch-Partenkirchen": 235,
    "Landsberg am Lech": 236,
    "Miesbach": 237,
    "Mühldorf a. Inn": 238,
    "München": 239,
    "Neuburg-Schrobenhausen": 240,
    "Pfaffenhofen a.d. Ilm": 241,
    "Rosenheim": 242,
    "Starnberg": 243,
    "Traunstein": 244,
    "Weilheim-Schongau": 245,
    "Deggendorf": 249,
    "Freyung-Grafenau": 250,
    "Kelheim": 251,
    "Landshut": 252,
    "Passau": 253,
    "Regen": 254,
    "Rottal-Inn": 255,
    "Straubing-Bogen": 256,
    "Dingolfing-Landau": 257,
    "Amberg-Sulzbach": 261,
    "Cham": 262,
    "Neumarkt i.d. OPf.": 263,
    "Neustadt a.d. Waldnaab": 264,
    "Regensburg": 265,
    "Schwandorf": 266,
    "Tirschenreuth": 267,
    "Bamberg": 272,
    "Bayreuth": 273,
    "Coburg": 274,
    "Forchheim": 275,
    "Hof": 276,
    "Kronach": 277,
    "Kulmbach": 278,
    "Lichtenfels": 279,
    "Wunsiedel i. Fichtelgebirge": 280,
    "Ansbach": 286,
    "Erlangen-Höchstadt": 287,
    "Fürth": 288,
    "Nürnberger Land": 289,
    "Neustadt a.d. Aisch-Bad Windsheim": 290,
    "Roth": 291,
    "Weißenburg-Gunzenhausen": 292,
    "Aschaffenburg": 296,
    "Bad Kissingen": 297,
    "Rhön-Grabfeld": 298,
    "Haßberge": 299,
    "Kitzingen": 300,
    "Miltenberg": 301,
    "Main-Spessart": 302,
    "Schweinfurt": 303,
    "Würzburg": 304,
    "Aichach-Friedberg": 309,
    "Augsburg": 310,
    "Dillingen a.d. Donau": 311,
    "Günzburg": 312,
    "Neu-Ulm": 313,
    "Lindau (Bodensee)": 314,
    "Ostallgäu": 315,
    "Unterallgäu": 316,
    "Donau-Ries": 317,
    "Oberallgäu": 318,
    "Regionalverband Saarbrücken": 319,
    "Merzig-Wadern": 320,
    "Neunkirchen": 321,
    "Saarlouis": 322,
    "Saarpfalz-Kreis": 323,
    "St. Wendel": 324,
    "Barnim": 330,
    "Dahme-Spreewald": 331,
    "Elbe-Elster": 332,
    "Havelland": 333,
    "Märkisch-Oderland": 334,
    "Oberhavel": 335,
    "Oberspreewald-Lausitz": 336,
    "Oder-Spree": 337,
    "Ostprignitz-Ruppin": 338,
    "Potsdam-Mittelmark": 339,
    "Prignitz": 340,
    "Spree-Neiße": 341,
    "Teltow-Fläming": 342,
    "Uckermark": 343,
    "Mecklenburgische Seenplatte": 346,
    "Rostock": 347,
    "Vorpommern-Rügen": 348,
    "Nordwestmecklenburg": 349,
    "Vorpommern-Greifswald": 350,
    "Ludwigslust-Parchim": 351,
    "Erzgebirgskreis": 353,
    "Mittelsachsen": 354,
    "Vogtlandkreis": 355,
    "Zwickau": 356,
    "Bautzen": 358,
    "Görlitz": 359,
    "Meißen": 360,
    "Sächsische Schweiz-Osterzgebirge": 361,
    "Leipzig": 363,
    "Nordsachsen": 364,
    "Altmarkkreis Salzwedel": 368,
    "Anhalt-Bitterfeld": 369,
    "Börde": 370,
    "Burgenlandkreis": 371,
    "Harz": 372,
    "Jerichower Land": 373,
    "Mansfeld-Südharz": 374,
    "Saalekreis": 375,
    "Salzlandkreis": 376,
    "Stendal": 377,
    "Wittenberg": 378,
    "Eichsfeld": 385,
    "Nordhausen": 386,
    "Wartburgkreis": 387,
    "Unstrut-Hainich-Kreis": 388,
    "Kyffhäuserkreis": 389,
    "Schmalkalden-Meiningen": 390,
    "Gotha": 391,
    "Sömmerda": 392,
    "Hildburghausen": 393,
    "Ilm-Kreis": 394,
    "Weimarer Land": 395,
    "Sonneberg": 396,
    "Saalfeld-Rudolstadt": 397,
    "Saale-Holzland-Kreis": 398,
    "Saale-Orla-Kreis": 399,
    "Greiz": 400,
    "Altenburger Land": 401
  };
  let stadtkreisids = {
    "Stuttgart": 179,
    "Heilbronn": 185,
    "Baden-Baden": 192,
    "Karlsruhe": 193,
    "Heidelberg": 196,
    "Mannheim": 197,
    "Pforzheim": 200,
    "Freiburg im Breisgau": 204,
    "Ulm": 217
  };
  let kreisids = {
    "Dithmarschen": 5,
    "Herzogtum Lauenburg": 6,
    "Nordfriesland": 7,
    "Ostholstein": 8,
    "Pinneberg": 9,
    "Plön": 10,
    "Rendsburg-Eckernförde": 11,
    "Schleswig-Flensburg": 12,
    "Segeberg": 13,
    "Steinburg": 14,
    "Stormarn": 15,
    "Kleve": 74,
    "Mettmann": 75,
    "Rhein-Kreis Neuss": 76,
    "Viersen": 77,
    "Wesel": 78,
    "Städteregion Aachen": 82,
    "Düren": 83,
    "Rhein-Erft-Kreis": 84,
    "Euskirchen": 85,
    "Heinsberg": 86,
    "Oberbergischer Kreis": 87,
    "Rheinisch-Bergischer Kreis": 88,
    "Rhein-Sieg-Kreis": 89,
    "Borken": 93,
    "Coesfeld": 94,
    "Recklinghausen": 95,
    "Steinfurt": 96,
    "Warendorf": 97,
    "Gütersloh": 99,
    "Herford": 100,
    "Höxter": 101,
    "Lippe": 102,
    "Minden-Lübbecke": 103,
    "Paderborn": 104,
    "Ennepe-Ruhr-Kreis": 110,
    "Hochsauerlandkreis": 111,
    "Märkischer Kreis": 112,
    "Olpe": 113,
    "Siegen-Wittgenstein": 114,
    "Soest": 115,
    "Unna": 116
  };
  let bezirkids = {
    "Berlin Reinickendorf": 404,
    "Berlin Charlottenburg-Wilmersdorf": 405,
    "Berlin Treptow-Köpenick": 406,
    "Berlin Pankow": 407,
    "Berlin Neukölln": 408,
    "Berlin Lichtenberg": 409,
    "Berlin Marzahn-Hellersdorf": 410,
    "Berlin Spandau": 411,
    "Berlin Steglitz-Zehlendorf": 412,
    "Berlin Mitte": 413,
    "Berlin Friedrichshain-Kreuzberg": 414,
    "Berlin Tempelhof-Schöneberg": 415
  }
  switch (type) {
    case "Stadt":
      console.log(name);
      let id = stadtids[name];
      return id;
      break;
    case "Landkreis":
      let id1 = lkids[name];
      return id1;
      break;
    case "Kreis":
      let id2 = kreisids[name];
      return id2;
      break;
    case "Stadtkreis":
      let id3 = stadtkreisids[name];
      return id3;
      break;
    case "Bezirk":
      let id4 = bezirkids[name];
      return id4;
      break;
  }
}

async function useData(id, msg) {
  let cov_api_url = `https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_Landkreisdaten/FeatureServer/0/query?where=OBJECTID=${id}&outFields=Shape__Length,last_update,cases7_per_100k&outSR=4326&f=json`;
  let cov_response = await fetch(cov_api_url);
  let cov_data = await cov_response.json();
  const {
    cases7_per_100k,
    last_update
  } = cov_data.features[0].attributes;
  msg.channel.send((Math.round(cases7_per_100k * 100) / 100) + ' am ' + last_update);
}